<p>std::throw_with_nested will create a class inherited from std::std::nested_exception and user exception then it will get current exception and user exception in it then throw.<br />
Ex)<br />
std::throw_with_nested(MyException());</p>
